CREATE TABLE IF NOT EXISTS franchiseoperationalworkflow (
  id VARCHAR(191) NOT NULL,
  tenantId VARCHAR(191) NOT NULL,
  businessPartnerId VARCHAR(191) NOT NULL,
  franchiseId VARCHAR(191) NOT NULL,
  centerId VARCHAR(191) NULL,
  operationalNotificationId VARCHAR(191) NULL,
  notificationFingerprint VARCHAR(191) NOT NULL,
  notificationType VARCHAR(191) NOT NULL,
  queueType VARCHAR(191) NOT NULL DEFAULT 'REVIEW',
  status VARCHAR(191) NOT NULL DEFAULT 'OPEN',
  currentActionRole VARCHAR(191) NULL,
  severity VARCHAR(191) NOT NULL,
  title VARCHAR(191) NOT NULL,
  summary TEXT NOT NULL,
  metricKey VARCHAR(191) NULL,
  thresholdValue DOUBLE NULL,
  observedValue DOUBLE NULL,
  deltaPercent DOUBLE NULL,
  sourceSnapshotDate DATETIME(3) NULL,
  sourceWindowKey VARCHAR(191) NULL,
  firstTriggeredAt DATETIME(3) NOT NULL,
  lastTriggeredAt DATETIME(3) NOT NULL,
  acknowledgedAt DATETIME(3) NULL,
  actionRequestedAt DATETIME(3) NULL,
  escalatedAt DATETIME(3) NULL,
  forwardedAt DATETIME(3) NULL,
  resolvedAt DATETIME(3) NULL,
  reopenedAt DATETIME(3) NULL,
  lastWorkflowActionAt DATETIME(3) NULL,
  workflowVersion INT NOT NULL DEFAULT 1,
  metadata JSON NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY fow_opn_uq (operationalNotificationId),
  UNIQUE KEY fow_t_fp_uq (tenantId, notificationFingerprint),
  KEY fow_t_fr_q_upd_i (tenantId, franchiseId, queueType, updatedAt),
  KEY fow_t_fr_st_upd_i (tenantId, franchiseId, status, updatedAt),
  KEY fow_t_ce_st_i (tenantId, centerId, status),
  KEY fow_t_bp_st_i (tenantId, businessPartnerId, status),
  KEY fow_t_sev_st_i (tenantId, severity, status),
  KEY fow_t_wfv_i (tenantId, workflowVersion),
  CONSTRAINT fow_tenant_fk FOREIGN KEY (tenantId) REFERENCES tenant(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fow_bp_fk FOREIGN KEY (businessPartnerId) REFERENCES businesspartner(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fow_fr_fk FOREIGN KEY (franchiseId) REFERENCES franchiseprofile(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fow_ce_fk FOREIGN KEY (centerId) REFERENCES centerprofile(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fow_opn_fk FOREIGN KEY (operationalNotificationId) REFERENCES operationalnotification(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS franchiseoperationalworkflowhistory (
  id VARCHAR(191) NOT NULL,
  workflowId VARCHAR(191) NOT NULL,
  tenantId VARCHAR(191) NOT NULL,
  businessPartnerId VARCHAR(191) NOT NULL,
  franchiseId VARCHAR(191) NOT NULL,
  centerId VARCHAR(191) NULL,
  fromStatus VARCHAR(191) NULL,
  toStatus VARCHAR(191) NOT NULL,
  actionType VARCHAR(191) NOT NULL,
  actorUserId VARCHAR(191) NULL,
  actorRole VARCHAR(191) NULL,
  expectedVersion INT NOT NULL,
  resultingVersion INT NOT NULL,
  reason TEXT NULL,
  notes TEXT NULL,
  metadata JSON NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY fowh_wf_ct_i (workflowId, createdAt),
  KEY fowh_t_fr_ct_i (tenantId, franchiseId, createdAt),
  KEY fowh_t_ce_ct_i (tenantId, centerId, createdAt),
  KEY fowh_t_usr_ct_i (tenantId, actorUserId, createdAt),
  CONSTRAINT fowh_wf_fk FOREIGN KEY (workflowId) REFERENCES franchiseoperationalworkflow(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fowh_tenant_fk FOREIGN KEY (tenantId) REFERENCES tenant(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fowh_bp_fk FOREIGN KEY (businessPartnerId) REFERENCES businesspartner(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fowh_fr_fk FOREIGN KEY (franchiseId) REFERENCES franchiseprofile(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fowh_ce_fk FOREIGN KEY (centerId) REFERENCES centerprofile(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fowh_actor_fk FOREIGN KEY (actorUserId) REFERENCES authuser(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS franchiseoperationalworkflowtask (
  id VARCHAR(191) NOT NULL,
  workflowId VARCHAR(191) NOT NULL,
  tenantId VARCHAR(191) NOT NULL,
  businessPartnerId VARCHAR(191) NOT NULL,
  franchiseId VARCHAR(191) NOT NULL,
  centerId VARCHAR(191) NULL,
  targetRole VARCHAR(191) NOT NULL,
  targetUserId VARCHAR(191) NULL,
  taskType VARCHAR(191) NOT NULL,
  state VARCHAR(191) NOT NULL DEFAULT 'OPEN',
  dueAt DATETIME(3) NULL,
  completedAt DATETIME(3) NULL,
  escalatedAt DATETIME(3) NULL,
  resolvedAt DATETIME(3) NULL,
  escalationCount INT NOT NULL DEFAULT 0,
  metadata JSON NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY fowt_t_role_st_d_i (tenantId, targetRole, state, dueAt),
  KEY fowt_t_usr_st_d_i (tenantId, targetUserId, state, dueAt),
  KEY fowt_wf_st_i (workflowId, state),
  KEY fowt_t_fr_st_i (tenantId, franchiseId, state),
  KEY fowt_t_ce_st_i (tenantId, centerId, state),
  CONSTRAINT fowt_wf_fk FOREIGN KEY (workflowId) REFERENCES franchiseoperationalworkflow(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fowt_tenant_fk FOREIGN KEY (tenantId) REFERENCES tenant(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fowt_bp_fk FOREIGN KEY (businessPartnerId) REFERENCES businesspartner(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fowt_fr_fk FOREIGN KEY (franchiseId) REFERENCES franchiseprofile(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fowt_ce_fk FOREIGN KEY (centerId) REFERENCES centerprofile(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fowt_target_fk FOREIGN KEY (targetUserId) REFERENCES authuser(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS franchiseoperationalescalation (
  id VARCHAR(191) NOT NULL,
  workflowId VARCHAR(191) NOT NULL,
  tenantId VARCHAR(191) NOT NULL,
  businessPartnerId VARCHAR(191) NOT NULL,
  franchiseId VARCHAR(191) NOT NULL,
  centerId VARCHAR(191) NULL,
  escalationType VARCHAR(191) NOT NULL,
  severity VARCHAR(191) NOT NULL,
  state VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
  triggeredAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  acknowledgedAt DATETIME(3) NULL,
  forwardedAt DATETIME(3) NULL,
  resolvedAt DATETIME(3) NULL,
  escalationReason TEXT NULL,
  metadata JSON NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY foe_t_fr_st_tr_i (tenantId, franchiseId, state, triggeredAt),
  KEY foe_wf_st_i (workflowId, state),
  KEY foe_t_ce_st_i (tenantId, centerId, state),
  CONSTRAINT foe_wf_fk FOREIGN KEY (workflowId) REFERENCES franchiseoperationalworkflow(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT foe_tenant_fk FOREIGN KEY (tenantId) REFERENCES tenant(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT foe_bp_fk FOREIGN KEY (businessPartnerId) REFERENCES businesspartner(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT foe_fr_fk FOREIGN KEY (franchiseId) REFERENCES franchiseprofile(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT foe_ce_fk FOREIGN KEY (centerId) REFERENCES centerprofile(id) ON DELETE SET NULL ON UPDATE CASCADE
);