import { Router } from "express";
import { authenticate } from "../middleware/authenticate.js";
import { enforceMustChangePassword } from "../middleware/enforce-must-change-password.js";
import { enforceSubscription } from "../middleware/enforce-subscription.js";
import { getHealth } from "../controllers/health.controller.js";
import { authRouter } from "./auth.routes.js";
import { superadminRouter } from "./superadmin.routes.js";
import { hierarchyRouter } from "./hierarchy.routes.js";
import { levelsRouter } from "./levels.routes.js";
import { studentsRouter } from "./students.routes.js";
import { worksheetsRouter } from "./worksheets.routes.js";
import { competitionsRouter } from "./competitions.routes.js";
import { businessPartnersRouter } from "./business-partners.routes.js";
import { examTextbookRouter } from "./exam-textbook.routes.js";
import { centersRouter } from "./centers.routes.js";
import { adminAnalyticsRouter } from "./admin-analytics.routes.js";
import { adminAbuseFlagsRouter } from "./admin-abuse-flags.routes.js";
import { notificationsRouter } from "./notifications.routes.js";
import { teachersRouter } from "./teachers.routes.js";
import { submissionsRouter } from "./submissions.routes.js";
import { financialReportingRouter } from "./financial-reporting.routes.js";
import { ledgerRouter } from "./ledger.routes.js";
import { auditLogsRouter } from "./audit-logs.routes.js";
import { marginsRouter } from "./margins.routes.js";
import { settlementsRouter } from "./settlements.routes.js";
import { partnersRouter } from "./partners.routes.js";
import { coursesRouter } from "./courses.routes.js";
import { catalogRouter } from "./catalog.routes.js";
import { questionBankRouter } from "./question-bank.routes.js";
import { partnerRouter } from "./partner.routes.js";
import { franchiseRouter } from "./franchise.routes.js";
import { franchisesRouter } from "./franchises.routes.js";
import { batchesRouter } from "./batches.routes.js";
import { enrollmentsRouter } from "./enrollments.routes.js";
import { attendanceRouter } from "./attendance.routes.js";
import { centerRouter } from "./center.routes.js";
import { centerAnalyticsRouter } from "./center-analytics.routes.js";
import { teacherAnalyticsRouter } from "./teacher-analytics.routes.js";
import { teacherPublicRouter } from "./teacher-public.routes.js";
import { teacherRouter } from "./teacher.routes.js";
import { studentRouter } from "./student.routes.js";
import { examCyclesRouter } from "./exam-cycles.routes.js";
import { brandingRouter } from "./branding.routes.js";
import { practiceAllocationRouter } from "./practice-allocation.routes.js";
import { publicCertificateRouter } from "./public-certificate.routes.js";

const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/teacher", teacherPublicRouter);
apiRouter.use("/public/certificates", publicCertificateRouter);
apiRouter.get("/health", getHealth);
apiRouter.use(authenticate);
apiRouter.use(enforceMustChangePassword);
apiRouter.use(enforceSubscription());

apiRouter.use("/superadmins", superadminRouter);
apiRouter.use("/superadmin", superadminRouter);
apiRouter.use("/partners", partnersRouter);
apiRouter.use("/hierarchy", hierarchyRouter);
apiRouter.use("/levels", levelsRouter);
apiRouter.use("/students", studentsRouter);
apiRouter.use("/worksheets", worksheetsRouter);
apiRouter.use("/competitions", competitionsRouter);
apiRouter.use("/courses", coursesRouter);
apiRouter.use("/catalog", catalogRouter);
apiRouter.use("/question-bank", questionBankRouter);
apiRouter.use("/business-partners", businessPartnersRouter);
apiRouter.use("/exam-textbook", examTextbookRouter);
apiRouter.use("/centers", centersRouter);
apiRouter.use("/teachers", teachersRouter);
apiRouter.use("/submissions", submissionsRouter);
apiRouter.use("/reports", financialReportingRouter);
apiRouter.use("/ledger", ledgerRouter);
apiRouter.use("/audit-logs", auditLogsRouter);
apiRouter.use("/margins", marginsRouter);
apiRouter.use("/settlements", settlementsRouter);
apiRouter.use("/admin/analytics", adminAnalyticsRouter);
apiRouter.use("/admin/abuse-flags", adminAbuseFlagsRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/partner", partnerRouter);
apiRouter.use("/franchise", franchiseRouter);
apiRouter.use("/franchises", franchisesRouter);
apiRouter.use("/batches", batchesRouter);
apiRouter.use("/enrollments", enrollmentsRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/center", centerRouter);
apiRouter.use("/center/analytics", centerAnalyticsRouter);
apiRouter.use("/teacher/analytics", teacherAnalyticsRouter);
apiRouter.use("/teacher", teacherRouter);
apiRouter.use("/student", studentRouter);
apiRouter.use("/exam-cycles", examCyclesRouter);
apiRouter.use("/branding", brandingRouter);
apiRouter.use("/practice-allocations", practiceAllocationRouter);

export { apiRouter };
