import { useEffect, useMemo, useState } from "react";
import { DataTable, PaginationBar } from "../../components/DataTable";
import { LoadingState } from "../../components/LoadingState";
import { ErrorState } from "../../components/ErrorState";
import { ConfirmDialog } from "../../components/ConfirmDialog";
import { getFriendlyErrorMessage } from "../../utils/apiErrors";
import { listAbuseFlags, resolveAbuseFlag } from "../../services/abuseFlagsService";

const FLAG_TYPES = [
  "RAPID_SUBMISSION",
  "PERFECT_STREAK",
  "TIME_ANOMALY",
  "COMPETITION_SPIKE"
];

function formatDateTime(value) {
  if (!value) {
    return "-";
  }
  const d = new Date(value);
  if (!Number.isFinite(d.getTime())) {
    return String(value);
  }
  return d.toLocaleString();
}

function AbuseFlagsPage() {
  const [rows, setRows] = useState([]);
  const [limit, setLimit] = useState(20);
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const [flagType, setFlagType] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  const [resolveId, setResolveId] = useState(null);

  const offset = useMemo(() => (page - 1) * limit, [page, limit]);

  const load = async ({ nextPage = page, nextLimit = limit } = {}) => {
    setLoading(true);
    setError("");
    try {
      const data = await listAbuseFlags({
        page: nextPage,
        limit: nextLimit,
        ...(flagType ? { flagType } : {}),
        ...(from ? { from } : {}),
        ...(to ? { to } : {})
      });
      setRows(data?.data?.items || []);
      setTotal(Number(data?.data?.total || 0));
      setPage(Number(data?.data?.page || nextPage));
      setLimit(Number(data?.data?.limit || nextLimit));
    } catch (e) {
      setError(getFriendlyErrorMessage(e) || "Failed to load abuse flags.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load({ nextPage: 1, nextLimit: limit });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onResolve = async (row) => {
    if (!row?.id) {
      return;
    }
    setResolveId(row.id);
  };

  const executeResolve = async () => {
    const id = resolveId;
    setResolveId(null);
    try {
      await resolveAbuseFlag(id);
      await load({ nextPage: page, nextLimit: limit });
    } catch (e) {
      setError(getFriendlyErrorMessage(e) || "Failed to resolve abuse flag.");
    }
  };

  if (loading && !rows.length) {
    return <LoadingState label="Loading abuse flags..." />;
  }

  return (
    <section style={{ display: "grid", gap: 12 }}>
      <div>
        <h2 style={{ margin: 0 }}>Abuse Flags</h2>
        <p style={{ margin: "6px 0 0", color: "var(--color-text-muted)", fontSize: 13 }}>
          Review and resolve integrity alerts generated by backend detection rules.
        </p>
      </div>

      {error ? <ErrorState title="Failed to load" message={error} onRetry={() => load({ nextPage: page, nextLimit: limit })} /> : null}

      <div className="card" style={{ display: "grid", gap: 10 }}>
        <div style={{ display: "grid", gap: 10, gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))" }}>
          <label style={{ display: "grid", gap: 6 }}>
            <span style={{ fontSize: 12, color: "var(--color-text-muted)" }}>Flag Type</span>
            <select className="select" value={flagType} onChange={(e) => setFlagType(e.target.value)}>
              <option value="">All</option>
              {FLAG_TYPES.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </label>

          <label style={{ display: "grid", gap: 6 }}>
            <span style={{ fontSize: 12, color: "var(--color-text-muted)" }}>From (ISO / date)</span>
            <input className="input" value={from} onChange={(e) => setFrom(e.target.value)} placeholder="2026-02-01" />
          </label>

          <label style={{ display: "grid", gap: 6 }}>
            <span style={{ fontSize: 12, color: "var(--color-text-muted)" }}>To (ISO / date)</span>
            <input className="input" value={to} onChange={(e) => setTo(e.target.value)} placeholder="2026-02-28" />
          </label>
        </div>

        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
          <button
            className="button"
            type="button"
            style={{ width: "auto" }}
            onClick={() => load({ nextPage: 1, nextLimit: limit })}
            disabled={loading}
          >
            {loading ? "Loading..." : "Apply"}
          </button>
          <button
            className="button secondary"
            type="button"
            style={{ width: "auto" }}
            onClick={() => {
              setFlagType("");
              setFrom("");
              setTo("");
              void load({ nextPage: 1, nextLimit: limit });
            }}
            disabled={loading}
          >
            Reset
          </button>
        </div>
      </div>

      <DataTable
        columns={[
          { key: "createdAt", header: "Created", render: (r) => formatDateTime(r.createdAt) },
          { key: "flagType", header: "Type" },
          { key: "studentId", header: "Student" },
          { key: "resolvedAt", header: "Resolved", render: (r) => (r.resolvedAt ? formatDateTime(r.resolvedAt) : "No") },
          {
            key: "resolvedBy",
            header: "Resolved By",
            render: (r) => r?.resolvedBy?.email || "-"
          },
          {
            key: "actions",
            header: "Actions",
            render: (r) => (
              <button
                className="button secondary"
                type="button"
                style={{ width: "auto" }}
                onClick={() => void onResolve(r)}
                disabled={Boolean(r?.resolvedAt)}
              >
                Resolve
              </button>
            )
          }
        ]}
        rows={rows}
        keyField="id"
      />

      <PaginationBar
        limit={limit}
        offset={offset}
        count={rows.length}
        total={total}
        onChange={(next) => {
          const nextLimit = next.limit;
          const nextPage = Math.floor(next.offset / nextLimit) + 1;
          setLimit(nextLimit);
          setPage(nextPage);
          void load({ nextPage, nextLimit });
        }}
      />

      <ConfirmDialog
        open={!!resolveId}
        title="Resolve Abuse Flag"
        message="Are you sure you want to resolve this abuse flag?"
        confirmLabel="Resolve"
        onCancel={() => setResolveId(null)}
        onConfirm={() => void executeResolve()}
      />
    </section>
  );
}

export { AbuseFlagsPage };
