import { ROLES } from "../types/auth";

const roleMenus = {
  [ROLES.SUPERADMIN]: [
    { section: "Overview" },
    { label: "🏠 Dashboard", to: "/superadmin/dashboard" },
    { label: "📈 Analytics", to: "/superadmin/analytics" },
    { label: "📊 Reports", to: "/superadmin/reports" },
    { section: "Hierarchy" },
    { label: "🤝 Business Partners", to: "/superadmin/business-partners" },
    { label: "🏢 Franchises", to: "/superadmin/franchises" },
    { label: "🏫 Centers / Schools", to: "/superadmin/centers" },
    { label: "🔍 Hierarchy Monitor", to: "/superadmin/hierarchy" },
    { section: "Academics" },
    { label: "📚 Courses", to: "/superadmin/courses" },
    { label: "🎮 Practice Features", to: "/superadmin/practice-features" },
    { label: "🎯 Exams", to: "/superadmin/exam-cycles" },
    { label: " Certificates", to: "/superadmin/certificates" },
    { label: "🏆 Competition", to: "/superadmin/competition" },
    { section: "Finance" },
    { label: "💰 Revenue", to: "/superadmin/revenue" },
    { label: "📑 Margins", to: "/superadmin/margins" },
    { label: "🏦 Settlements", to: "/superadmin/settlements" },
    { label: "📒 Ledger", to: "/superadmin/ledger" },
    { label: "📋 Subscriptions", to: "/superadmin/subscriptions" },
    { section: "System" },
    { label: "👥 Users", to: "/superadmin/users" },
    { label: "🚩 Abuse Flags", to: "/superadmin/abuse-flags" },
    { label: "📝 Audit Logs", to: "/superadmin/audit-logs" },
    { label: "🔔 Notifications", to: "/notifications" }
  ],
  [ROLES.CENTER]: [
    { section: "Home" },
    { label: "🏠 Dashboard", to: "/center/dashboard" },
    { section: "People" },
    { label: "👩‍🏫 Teachers", to: "/center/teachers" },
    { label: "🎓 Students", to: "/center/students" },
    { label: "👥 Batches", to: "/center/batches" },
    { label: "📋 Enrollments", to: "/center/enrollments" },
    { section: "Academics" },
    { label: "📚 Courses & Worksheets", to: "/center/worksheets" },
    { label: "🎮 Practice Features", to: "/center/practice-assignments" },
    { label: "🔄 Reassignment Queue", to: "/center/reassignment-requests" },
    { label: "🧪 Mock Tests", to: "/center/dashboard?section=mock-tests" },
    { label: "🎯 Exams", to: "/center/exam-cycles" },
    { label: "🏆 Competition", to: "/center/competition-enrollment" },
    { label: "📅 Attendance", to: "/center/attendance" },
    { label: "📋 Attendance History", to: "/center/attendance-history" },
    { label: "📊 Analytics", to: "/center/analytics" },
    { section: "Finance" },
    { label: "📊 Reports", to: "/center/reports" },
    { label: "💰 Settlements", to: "/center/settlements" },
    { section: "System" },
    { label: "🔔 Notifications", to: "/notifications" }
  ],
  [ROLES.TEACHER]: [
    { section: "Home" },
    { label: "🏠 Dashboard", to: "/teacher/dashboard" },
    { label: "👤 Profile", to: "/teacher/profile" },
    { section: "Teaching" },
    { label: "👥 My Batches", to: "/teacher/batches" },
    { label: "🎓 Assigned Students", to: "/teacher/students" },
    { label: "📝 Notes", to: "/teacher/notes" },
    { label: "📅 Attendance", to: "/teacher/attendance" },
    { section: "Academics" },
    { label: "📊 Result", to: "/teacher/results" },
    { label: "📚 Worksheets", to: "/teacher/worksheets" },
    { label: "🔄 Reassignment Queue", to: "/teacher/reassignment-requests" },
    { label: "🧪 Mock Tests", to: "/teacher/batches?section=mock-tests" },
    { label: "🧮 Virtual Abacus", to: "/teacher/virtual-abacus" },
    { label: "🎯 Exams", to: "/teacher/exam-cycles" },
    { label: "📊 Analytics", to: "/teacher/analytics" },
    { section: "System" },
    { label: "🔔 Notifications", to: "/notifications" }
  ],
  [ROLES.BP]: [
    { section: "Home" },
    { label: "🏠 Dashboard", to: "/bp/dashboard" },
    { label: "👤 Profile", to: "/bp/profile" },
    { section: "Hierarchy" },
    { label: "🏢 Franchises", to: "/bp/franchises" },
    { label: "🏫 Centers / Schools", to: "/bp/centers" },
    { label: "🎓 Students", to: "/bp/students" },
    { section: "Academics" },
    { label: "📚 Courses", to: "/bp/courses" },
    { label: "📝 Worksheets", to: "/bp/worksheets" },
    { label: "🎮 Practice Features", to: "/bp/practice-allocations" },
    { label: "🏅 Certificates", to: "/bp/certificates" },
    { label: "📜 Certificate Template", to: "/bp/certificate-template" },
    { label: "🎯 Exams", to: "/bp/exam-cycles" },
    { label: "🏆 Competition", to: "/bp/competition-requests" },
    { section: "Finance" },
    { label: "💰 Revenue", to: "/bp/revenue" },
    { label: "⚖️ Revenue Split", to: "/bp/revenue-split" },
    { label: "🏦 Settlements", to: "/bp/settlements" },
    { label: "📒 Ledger", to: "/bp/ledger" },
    { section: "System" },
    { label: "🔔 Notifications", to: "/notifications" }
  ],
  [ROLES.FRANCHISE]: [
    { section: "Home" },
    { label: "🏠 Dashboard", to: "/franchise/dashboard" },
    { label: "👤 Profile", to: "/franchise/profile" },
    { section: "Hierarchy" },
    { label: "🏫 Centers / Schools", to: "/franchise/centers" },
    { label: "🎓 Students", to: "/franchise/students" },
    { section: "Academics" },
    { label: "📚 Courses", to: "/franchise/courses" },
    { label: "📝 Worksheets", to: "/franchise/worksheets" },
    { label: "🎮 Practice Features", to: "/franchise/practice-allocations" },
    { label: "🎯 Exams", to: "/franchise/exam-cycles" },
    { label: "🏆 Competition", to: "/franchise/competition-requests" },
    { section: "Finance" },
    { label: "📊 Reports", to: "/franchise/reports" },
    { label: "📑 Margins", to: "/franchise/margins" },
    { label: "🏦 Settlements", to: "/franchise/settlements" },
    { section: "System" },
    { label: "🔔 Notifications", to: "/notifications" }
  ],
  [ROLES.STUDENT]: [
    { section: "Home" },
    { label: "🏠 Dashboard", to: "/student/dashboard" },
    { label: "👤 Profile", to: "/student/profile" },
    { section: "Learning" },
    { label: "📚 My Course", to: "/student/my-course" },
    { label: "📝 Worksheets", to: "/student/worksheets" },
    { label: "✏️ Practice", to: "/student/practice" },
    { label: "🧮 Abacus Practice", to: "/student/abacus-practice" },
    { label: "🧮 Virtual Abacus", to: "/student/virtual-abacus" },
    { label: "📖 Materials", to: "/student/materials" },
    { section: "Exams & Results" },
    { label: "🧪 Mock Tests", to: "/student/mock-tests" },
    { label: "🎯 Exams", to: "/student/exams" },
    { label: "📊 Results", to: "/student/results" },
    { label: "📈 Progress", to: "/student/progress" },
    { label: "⚠️ Weak Topics", to: "/student/weak-topics" },
    { section: "Achievements" },
    { label: "🏆 Leaderboard", to: "/student/leaderboard" },
    { label: "🏅 Certificates", to: "/student/certificates" },
    { section: "Account" },
    { label: "📅 Attendance", to: "/student/attendance" },
    { label: "💰 Fees", to: "/student/fees" },
    { label: "📋 Enrollments", to: "/student/enrollments" },
    { label: "🤖 AI Playground", to: "/student/ai-playground" },
    { label: "🔔 Notifications", to: "/notifications" }
  ]
};

function getMenuForRole(role) {
  return roleMenus[role] || [];
}

export { getMenuForRole };
